In [1]:
import numpy as np
import cv2
import os

In [2]:
images = []
targets = []

In [3]:
with_mask_path  = 'data/with_mask/'
without_mask_path = 'data/without_mask/'

In [4]:
content = os.listdir(with_mask_path)
error_count = 1
for image in content:
    try:
        filename = with_mask_path + image
        #print(filename)
        img = cv2.imread(filename)
        #print("Img : ",img)
        img_grey = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
        resized_img = cv2.resize(img_grey, (100, 100))
        images.append(resized_img)
        targets.append(0)
    except:
        print("Filename Error", error_count)
        error_count += 1
print("Completed")

Completed


In [5]:
content = os.listdir(without_mask_path)
error_count = 1
for image in content:
    try:
        filename = without_mask_path + image
        #print(filename)
        img = cv2.imread(filename)
        #print("Img : ",img)
        img_grey = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
        resized_img = cv2.resize(img_grey, (100, 100))
        images.append(resized_img)
        targets.append(1)
    except:
        print("Filename Error", error_count)
        error_count += 1
print("Completed")

Completed


In [6]:
len(images), len(targets)

(7553, 7553)

In [7]:
images

[array([[51, 52, 64, ..., 85,  9, 33],
        [51, 55, 62, ..., 20, 60, 40],
        [54, 52, 48, ..., 71, 52,  4],
        ...,
        [74, 77, 70, ..., 14,  5, 51],
        [64, 68, 74, ...,  5, 12,  9],
        [60, 60, 56, ..., 15, 15, 15]], dtype=uint8),
 array([[ 78,  84,  90, ...,  62,  58,  60],
        [ 79,  75,  68, ...,  48,  48,  47],
        [ 81,  78,  58, ...,  54,  51,  53],
        ...,
        [134, 141, 133, ..., 164, 157, 149],
        [146, 148, 138, ..., 177, 170, 153],
        [155, 150, 140, ..., 181, 178, 168]], dtype=uint8),
 array([[ 18,  24,  27, ...,  44,  58, 148],
        [ 25,  30,  29, ...,  52,  50, 100],
        [ 30,  31,  28, ...,  60,  54,  67],
        ...,
        [ 18,  13,   8, ...,  28,  34,  42],
        [ 16,  10,   6, ...,  28,  34,  42],
        [ 16,  11,   8, ...,  28,  36,  43]], dtype=uint8),
 array([[134, 133, 130, ...,  25,  30,  31],
        [137, 136, 138, ...,  22,  32,  30],
        [140, 132, 139, ...,  15,  33,  33],
       

In [8]:
images[0]

array([[51, 52, 64, ..., 85,  9, 33],
       [51, 55, 62, ..., 20, 60, 40],
       [54, 52, 48, ..., 71, 52,  4],
       ...,
       [74, 77, 70, ..., 14,  5, 51],
       [64, 68, 74, ...,  5, 12,  9],
       [60, 60, 56, ..., 15, 15, 15]], dtype=uint8)

In [9]:
images = np.array(images)/255.0

In [10]:
images

array([[[0.2       , 0.20392157, 0.25098039, ..., 0.33333333,
         0.03529412, 0.12941176],
        [0.2       , 0.21568627, 0.24313725, ..., 0.07843137,
         0.23529412, 0.15686275],
        [0.21176471, 0.20392157, 0.18823529, ..., 0.27843137,
         0.20392157, 0.01568627],
        ...,
        [0.29019608, 0.30196078, 0.2745098 , ..., 0.05490196,
         0.01960784, 0.2       ],
        [0.25098039, 0.26666667, 0.29019608, ..., 0.01960784,
         0.04705882, 0.03529412],
        [0.23529412, 0.23529412, 0.21960784, ..., 0.05882353,
         0.05882353, 0.05882353]],

       [[0.30588235, 0.32941176, 0.35294118, ..., 0.24313725,
         0.22745098, 0.23529412],
        [0.30980392, 0.29411765, 0.26666667, ..., 0.18823529,
         0.18823529, 0.18431373],
        [0.31764706, 0.30588235, 0.22745098, ..., 0.21176471,
         0.2       , 0.20784314],
        ...,
        [0.5254902 , 0.55294118, 0.52156863, ..., 0.64313725,
         0.61568627, 0.58431373],
        [0.5

In [11]:
images = np.resize(images, (7553, 100, 100, 1))

In [12]:
images

array([[[[0.2       ],
         [0.20392157],
         [0.25098039],
         ...,
         [0.33333333],
         [0.03529412],
         [0.12941176]],

        [[0.2       ],
         [0.21568627],
         [0.24313725],
         ...,
         [0.07843137],
         [0.23529412],
         [0.15686275]],

        [[0.21176471],
         [0.20392157],
         [0.18823529],
         ...,
         [0.27843137],
         [0.20392157],
         [0.01568627]],

        ...,

        [[0.29019608],
         [0.30196078],
         [0.2745098 ],
         ...,
         [0.05490196],
         [0.01960784],
         [0.2       ]],

        [[0.25098039],
         [0.26666667],
         [0.29019608],
         ...,
         [0.01960784],
         [0.04705882],
         [0.03529412]],

        [[0.23529412],
         [0.23529412],
         [0.21960784],
         ...,
         [0.05882353],
         [0.05882353],
         [0.05882353]]],


       [[[0.30588235],
         [0.32941176],
         [0.35

In [13]:
from keras.utils import np_utils

In [14]:
targets[-10:]

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [15]:
targets = np_utils.to_categorical(targets)

In [16]:
targets

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       ...,
       [0., 1.],
       [0., 1.],
       [0., 1.]], dtype=float32)

In [17]:
from sklearn.model_selection import train_test_split

In [18]:
images.shape[0]

7553

In [19]:
targets.shape[0]

7553

In [20]:
X_train, X_test, Y_train, Y_test = train_test_split(images, targets)

In [21]:
X_train.shape, X_test.shape, Y_train.shape, Y_test.shape

((5664, 100, 100, 1), (1889, 100, 100, 1), (5664, 2), (1889, 2))

In [22]:
from keras.models import Sequential
from keras.layers import Dense, Flatten, Conv2D, MaxPooling2D, Activation, Dropout
from keras.optimizers import SGD
from keras.callbacks import ModelCheckpoint

In [23]:
model = Sequential()

In [24]:
model.add(Conv2D(200, (3,3), input_shape=(100, 100, 1)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Conv2D(100, (3,3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Dropout(0.3))
model.add(Flatten())

model.add(Dense(50, activation='relu'))
model.add(Dense(2, activation='softmax'))

model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [26]:
cp = ModelCheckpoint('model-best', verbose=0, save_best_only=True)
model.fit(X_train, Y_train, epochs = 5, callbacks=[cp], validation_split=0.2)

Epoch 1/5
142/142 [==============================] - 212s 1s/step - loss: 0.3213 - accuracy: 0.8570 - val_loss: 0.3722 - val_accuracy: 0.8376
INFO:tensorflow:Assets written to: model-best\assets
Epoch 2/5
142/142 [==============================] - 214s 2s/step - loss: 0.2460 - accuracy: 0.8960 - val_loss: 0.3338 - val_accuracy: 0.8623
INFO:tensorflow:Assets written to: model-best\assets
Epoch 3/5
142/142 [==============================] - 217s 2s/step - loss: 0.1847 - accuracy: 0.9325 - val_loss: 0.3726 - val_accuracy: 0.8491
Epoch 4/5
142/142 [==============================] - 234s 2s/step - loss: 0.1313 - accuracy: 0.9517 - val_loss: 0.3818 - val_accuracy: 0.8667
Epoch 5/5
142/142 [==============================] - 231s 2s/step - loss: 0.1128 - accuracy: 0.9581 - val_loss: 0.4085 - val_accuracy: 0.8623


In [27]:
from keras.models import load_model

In [28]:
mod = load_model('model-best')

In [33]:
face_detect = cv2.CascadeClassifier('C:/Users/K MANGOTRA/anaconda3/Lib/site-packages/cv2/data/haarcascade_frontalface_default.xml')

In [ ]:
source = cv2.VideoCapture(0)
while 1:
    not_to_use, image = source.read()
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    faces = face_detect.detectMultiScale(gray, 1.5, 1)
    for (x, y, w, h) in faces:
        face_roi = gray[y:y+w, x:x+h]
        resized_image = cv2.resize(face_roi, (100, 100))
        normalized_image = resized_image/255
        reshaped_face = np.reshape(normalized_image, (1, 100, 100, 1))
        result = mod.predict(reshaped_face)[0]
        #print("Result : ", result)
        if result[0] >  result[1]:
            cv2.rectangle(image, (x, y), (x + w, y + h), (0, 255, 0), 2)
            cv2.putText(image, "Safe", (x, y), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 255, 0), 2)
        
        if result[1] >  result[0]:
            cv2.rectangle(image, (x, y), (x + w, y + h), (0, 0, 255), 2)
            cv2.putText(image, "Not Safe", (x, y), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 0, 255), 2)
        
            
    cv2.imshow('Verzeo Project', image)
    key = cv2.waitKey(1)
    if key == 27:
        break
cv2.destroyAllWindows()
source.release()